apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
spec:
  selector:
    matchLabels:
      app: vets
  replicas: 1
  template:
    metadata:
      labels:
        app: vets
    spec:
      initContainers:
        - image: apache/skywalking-base:8.1.0-es7
          name: sw-agent-sidecar
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            [
              "-c",
              "cp -r /skywalking/agent /sidecar",
            ]
          volumeMounts:
            - mountPath: /sidecar
              name: sw-agent
      containers:
        - name: vets
          image: spring2go/spring-petclinic-vets-service:1.0.0.RELEASE
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/sidecar/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: petclinic-vets
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-oap.defaul.svc.cluster.localt:11800 # FQDN: servicename.namespacename.svc.cluster.local
            - name: SERVER_PORT
              value: "8080"
          volumeMounts:
            - mountPath: /sidecar
              name: sw-agent
      volumes:
        - name: sw-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vets
  labels:
    svc: vets
spec:
  selector:
    app: vets
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
