apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
spec:
  selector:
    matchLabels:
      app: visits
  replicas: 1
  template:
    metadata:
      labels:
        app: visits
    spec:
      initContainers:
        - image: apache/skywalking-base:8.1.0-es7 
          name: sw-agent-sidecar
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            [
              "-c",
              "cp -r /skywalking/agent /sidecar",
            ]
          volumeMounts:
            - mountPath: /sidecar
              name: sw-agent
      containers:
        - name: visits
          image: spring2go/spring-petclinic-visits-service:1.0.0.RELEASE
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/sidecar/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: petclinic-visits
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-oap.default:11800 # FQDN: servicename.namespacename.svc.cluster.local
            - name: SERVER_PORT
              value: "8080"
          volumeMounts:
            - mountPath: /sidecar
              name: sw-agent
      volumes:
        - name: sw-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: visits
  labels:
    svc: visits
spec:
  selector:
    app: visits
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
